# Generated by Django 5.2.8 on 2026-09-20 05:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('analyst', 'Art Analyst'), ('collector', 'Collector'), ('admin', 'Administrator')], default='collector', max_length=20)),
                ('bio', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('claimed_artist', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('original_image', models.ImageField(upload_to='artworks/')),
                ('status', models.CharField(choices=[('pending', 'Waiting for analysis'), ('processing', 'AI is analyzing...'), ('completed', 'Analysis done'), ('failed', 'Analysis failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artworks',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('is_likely_authentic', models.BooleanField()),
                ('risk_factors', models.JSONField(default=dict)),
                ('style_match_score', models.FloatField()),
                ('heatmap_image', models.ImageField(blank=True, upload_to='heatmaps/')),
                ('feature_vector', models.JSONField()),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.artwork')),
            ],
            options={
                'db_table': 'analysis_results',
                'ordering': ['-analysis_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(db_index=True, max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='reference_artworks/')),
                ('feature_vector', models.JSONField()),
                ('source', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'reference_artworks',
                'indexes': [models.Index(fields=['artist_name', 'period'], name='reference_a_artist__49c3ef_idx')],
            },
        ),
    ]
