# Generated by Django 5.2.8 on 2026-09-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='heatmap_image',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='heatmap_data',
            field=models.JSONField(default=list),
        ),
    ]
