# Generated by Django 5.2.8 on 2026-09-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_analysisresult_heatmap_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='top_matches',
            field=models.JSONField(default=list),
        ),
    ]
