# Generated by Django 5.2.8 on 2026-09-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_analysisresult_top_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
